export const types:any = {
    GET_STUDENT_LIST_REQUEST: 'GET_STUDENT_LIST_REQUEST',
    GET_STUDENT_LIST_SUCCESS: 'GET_STUDENT_LIST_SUCCESS',
    GET_STUDENT_LIST_FAILURE: 'GET_STUDENT_LIST_FAILURE',

    ADD_STUDENT_REQUEST: 'ADD_STUDENT_REQUEST',
    ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
    ADD_STUDENT_FAILURE: 'ADD_STUDENT_FAILURE',

    ADD_NEW_CLASS_REQUEST: 'ADD_NEW_CLASS_REQUEST',
    ADD_NEW_CLASS_SUCCESS: 'ADD_NEW_CLASS_SUCCESS',
    ADD_NEW_CLASS_FAILURE: 'ADD_NEW_CLASS_FAILURE',

    GET_GURU_LIST_REQUEST: 'GET_GURU_LIST_REQUEST',
    GET_GURU_LIST_SUCCESS: 'GET_GURU_LIST_SUCCESS',
    GET_GURU_LIST_FAILURE: 'GET_GURU_LIST_FAILURE',

    GET_CLASS_LIST_REQUEST: 'GET_CLASS_LIST_REQUEST',
    GET_CLASS_LIST_SUCCESS: 'GET_CLASS_LIST_SUCCESS',
    GET_CLASS_LIST_FAILURE: 'GET_CLASS_LIST_FAILURE',

    GET_CLASS_LIST_BY_RANGE_REQUEST: 'GET_CLASS_LIST_BY_RANGE_REQUEST',
    GET_CLASS_LIST_BY_RANGE_SUCCESS: 'GET_CLASS_LIST_BY_RANGE_SUCCESS',
    GET_CLASS_LIST_BY_RANGE_FAILURE: 'GET_CLASS_LIST_BY_RANGE_FAILURE',




    GET_CLASS_ATTANDANCE_REQUEST: 'GET_CLASS_ATTANDANCE_REQUEST',
    GET_CLASS_ATTANDANCE_SUCCESS: 'GET_CLASS_ATTANDANCE_SUCCESS',
    GET_CLASS_ATTANDANCE_FAILURE: 'GET_CLASS_ATTANDANCE_FAILURE',

    SET_SELECTED_CLASS_REQUEST: 'SET_SELECTED_CLASS_REQUEST',
    SET_SELECTED_CLASS_SUCCESS: 'SET_SELECTED_CLASS_SUCCESS',

    SEARCH_STUDENTS_REQUEST: 'SEARCH_STUDENTS_REQUEST',
    SEARCH_STUDENTS_SUCCESS: 'SEARCH_STUDENTS_SUCCESS',
    SEARCH_STUDENTS_FAILURE: 'SEARCH_STUDENTS_FAILURE',

    // NN=>Name, Number
    SEARCH_STUDENTS_BY_NN_REQUEST: 'SEARCH_STUDENTS_BY_NN_REQUEST',
    SEARCH_STUDENTS_BY_NN_SUCCESS: 'SEARCH_STUDENTS_BY_NN_SUCCESS',
    SEARCH_STUDENTS_BY_NN_FAILURE: 'SEARCH_STUDENTS_BY_NN_FAILURE',

    UPDATE_STUDENTS_ATTANDANCE_REQUEST: 'UPDATE_STUDENTS_ATTANDANCE_REQUEST',
    UPDATE_STUDENTS_ATTANDANCE_SUCCESS: 'UPDATE_STUDENTS_ATTANDANCE_SUCCESS',
    UPDATE_STUDENTS_ATTANDANCE_FAILURE: 'UPDATE_STUDENTS_ATTANDANCE_FAILURE',

    GET_STUDENT_TIMELINE_REQUEST: 'GET_STUDENT_TIMELINE_REQUEST',
    GET_STUDENT_TIMELINE_SUCCESS: 'GET_STUDENT_TIMELINE_SUCCESS',

    ADD_NEW_GURU_REQUEST: 'ADD_NEW_GURU_REQUEST',
    ADD_NEW_GURU_SUCCESS: 'ADD_NEW_GURU_SUCCESS',

    DELETE_GURU_REQUEST: 'DELETE_GURU_REQUEST',
    DELETE_GURU_SUCCESS: 'DELETE_GURU_SUCCESS',

    SET_AUTH_REQUEST: 'SET_AUTH_REQUEST',
    SET_AUTH_SUCCESS: 'SET_AUTH_SUCCESS',

    RESET_STATE_REQUEST: 'RESET_STATE_REQUEST',
    RESET_STATE_SUCCESS: 'RESET_STATE_SUCCESS',

    SET_SNACK_BAR_ACTION_REQUEST: 'SET_SNACK_BAR_ACTION_REQUEST',
    SET_SNACK_BAR_ACTION_ERROR: 'SET_SNACK_BAR_ACTION_ERROR',
    SET_SNACK_BAR_ACTION_WARNING : 'SET_SNACK_BAR_ACTION_WARNING',
    SET_SNACK_BAR_ACTION_INFO : 'SET_SNACK_BAR_ACTION_INFO',
    SET_SNACK_BAR_ACTION_SUCCESS: 'SET_SNACK_BAR_ACTION_SUCCESS',
    SET_SNACK_BAR_ACTION_OFF: 'SET_SNACK_BAR_ACTION_OFF',


    LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',

    SET_THEME_REQUEST: 'SET_THEME_REQUEST',
    SET_THEME_SUCCESS: 'SET_THEME_SUCCESS',

    
    SET_EMPTEY_CARD_ID: 'SET_EMPTEY_CARD_ID',
    IS_LOADING: 'IS_LOADING',
    REDIRECT_REQUEST: 'REDIRECT_REQUEST',
    REDIRECT_SUCCESS: 'REDIRECT_SUCCESS',
    REDIRECT_REQUEST_PARAMS: 'REDIRECT_REQUEST_PARAMS',
    IS_LOGGED_IN: 'IS_LOGGED_IN',
    RESET_STATE: 'RESET_STATE',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_LOADING_REQUEST: 'SET_LOADING_REQUEST',
    SET_LOADING_SUCCESS: 'SET_LOADING_SUCCESS',
    SET_TOTAL_STUDENT_COUNT: 'SET_TOTAL_STUDENT_COUNT',
};